GET http://localhost:5117/games

###
GET http://localhost:5117/games/1

### 
# Test returning nonexisting game Id, should return 404
GET http://localhost:5117/games/9999

###
POST http://localhost:5117/games
Content-Type: application/json

{
    "name": "Metroid Prime",
    "genre": "Action",
    "price": 39.99,
    "releaseDate": "2003-03-21"
}

###
PUT http://localhost:5117/games/1   
Content-Type: application/json

{
    "name": "Cult of Lambs ULTIMATE",
    "genre": "Action",
    "price": 30.00,
    "releaseDate": "2002-02-08"
}

###
# Test modify nonexisting game Id, should return 404
PUT http://localhost:5117/games/9999
Content-Type: application/json

{
    "name": "Cult of Lambs",
    "genre": "Action",
    "price": 30.00,
    "releaseDate": "2002-02-08"
}

###
DELETE http://localhost:5117/games/1

###
# Test deleting nonexisting game Id, should return 404
DELETE http://localhost:5117/games/9999
